-- ============================================================================
-- MIGRATION: 032_billing_inventory_reversal_traceability.sql
-- MODULE: Facturación (FAC-7 — Refactorización Definitiva de Reversión de Inventario)
-- DESCRIPTION:
--   1. Asegura columna movimiento_origen_id en admin.movimientos_inventario con FK e índice.
--   2. Crea tabla admin.detalle_factura_movimiento con PK INT4 GENERATED BY DEFAULT AS IDENTITY.
--   3. Crea tabla admin.regla_reversion_movimiento con PK INT4 GENERATED BY DEFAULT AS IDENTITY.
--   4. Inserta reglas iniciales configurables sin IDs hardcodeados (SAL_VENTA, SAL_ORDEN).
-- IDEMPOTENT: Sí
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. Columna movimiento_origen_id en admin.movimientos_inventario (Idempotente)
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'admin'
          AND table_name = 'movimientos_inventario'
          AND column_name = 'movimiento_origen_id'
    ) THEN
        ALTER TABLE admin.movimientos_inventario
        ADD COLUMN movimiento_origen_id INT4 NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.table_constraints
        WHERE table_schema = 'admin'
          AND table_name = 'movimientos_inventario'
          AND constraint_name = 'movimientos_movimiento_origen_fk'
    ) THEN
        ALTER TABLE admin.movimientos_inventario
        ADD CONSTRAINT movimientos_movimiento_origen_fk
        FOREIGN KEY (movimiento_origen_id)
        REFERENCES admin.movimientos_inventario (movimiento_inventario_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_movimientos_movimiento_origen
ON admin.movimientos_inventario (movimiento_origen_id)
WHERE movimiento_origen_id IS NOT NULL;

-- ----------------------------------------------------------------------------
-- 2. Tabla admin.detalle_factura_movimiento
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin.detalle_factura_movimiento (
    detalle_factura_movimiento_id INT4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    detalle_factura_id INT4 NOT NULL,
    movimiento_inventario_id INT4 NOT NULL,
    cantidad NUMERIC(14,4) NOT NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    usuario_registro INT4 NULL,

    CONSTRAINT pk_detalle_factura_movimiento
        PRIMARY KEY (detalle_factura_movimiento_id),

    CONSTRAINT fk_dfm_detalle_factura
        FOREIGN KEY (detalle_factura_id)
        REFERENCES admin.detalle_factura(detalle_factura_id),

    CONSTRAINT fk_dfm_movimiento
        FOREIGN KEY (movimiento_inventario_id)
        REFERENCES admin.movimientos_inventario(movimiento_inventario_id),

    CONSTRAINT uq_dfm_detalle_movimiento
        UNIQUE (detalle_factura_id, movimiento_inventario_id),

    CONSTRAINT ck_dfm_cantidad
        CHECK (cantidad > 0)
);

CREATE INDEX IF NOT EXISTS idx_dfm_detalle_factura
ON admin.detalle_factura_movimiento (detalle_factura_id);

CREATE INDEX IF NOT EXISTS idx_dfm_movimiento
ON admin.detalle_factura_movimiento (movimiento_inventario_id);

-- ----------------------------------------------------------------------------
-- 3. Tabla admin.regla_reversion_movimiento
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS admin.regla_reversion_movimiento (
    regla_reversion_movimiento_id INT4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_movimiento_origen_id INT4 NOT NULL,
    contexto_reversion VARCHAR(50) NOT NULL,
    tipo_movimiento_reversion_id INT4 NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    descripcion VARCHAR(255) NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    fecha_actualizacion TIMESTAMPTZ NULL,
    usuario_registro INT4 NULL,
    usuario_actualizacion INT4 NULL,

    CONSTRAINT pk_regla_reversion_movimiento
        PRIMARY KEY (regla_reversion_movimiento_id),

    CONSTRAINT fk_reg_rev_origen
        FOREIGN KEY (tipo_movimiento_origen_id)
        REFERENCES admin.tipo_movimiento_inventario(tipo_movimiento_id),

    CONSTRAINT fk_reg_rev_destino
        FOREIGN KEY (tipo_movimiento_reversion_id)
        REFERENCES admin.tipo_movimiento_inventario(tipo_movimiento_id),

    CONSTRAINT uq_regla_reversion
        UNIQUE (tipo_movimiento_origen_id, contexto_reversion)
);

CREATE INDEX IF NOT EXISTS idx_reg_rev_origen
ON admin.regla_reversion_movimiento (tipo_movimiento_origen_id);

CREATE INDEX IF NOT EXISTS idx_reg_rev_contexto
ON admin.regla_reversion_movimiento (contexto_reversion);

CREATE INDEX IF NOT EXISTS idx_reg_rev_activo
ON admin.regla_reversion_movimiento (activo);

-- ----------------------------------------------------------------------------
-- 4. Reglas Iniciales de Reversión (Sin IDs hardcodeados)
-- ----------------------------------------------------------------------------
-- 4.1. SAL_VENTA + ANULACION_FACTURA -> DEV_VENTA
INSERT INTO admin.regla_reversion_movimiento (
    tipo_movimiento_origen_id,
    contexto_reversion,
    tipo_movimiento_reversion_id,
    descripcion
)
SELECT
    origen.tipo_movimiento_id,
    'ANULACION_FACTURA',
    reverso.tipo_movimiento_id,
    'Reversión de salida comercial por anulación de factura'
FROM admin.tipo_movimiento_inventario origen
JOIN admin.tipo_movimiento_inventario reverso
  ON reverso.codigo = 'DEV_VENTA'
WHERE origen.codigo = 'SAL_VENTA'
ON CONFLICT (tipo_movimiento_origen_id, contexto_reversion) DO UPDATE
SET tipo_movimiento_reversion_id = EXCLUDED.tipo_movimiento_reversion_id,
    descripcion = EXCLUDED.descripcion,
    activo = TRUE;

-- 4.2. SAL_ORDEN + ANULACION_FACTURA -> DEV_VENTA
INSERT INTO admin.regla_reversion_movimiento (
    tipo_movimiento_origen_id,
    contexto_reversion,
    tipo_movimiento_reversion_id,
    descripcion
)
SELECT
    origen.tipo_movimiento_id,
    'ANULACION_FACTURA',
    reverso.tipo_movimiento_id,
    'Reversión de consumo de orden de trabajo por anulación de factura'
FROM admin.tipo_movimiento_inventario origen
JOIN admin.tipo_movimiento_inventario reverso
  ON reverso.codigo = 'DEV_VENTA'
WHERE origen.codigo = 'SAL_ORDEN'
ON CONFLICT (tipo_movimiento_origen_id, contexto_reversion) DO UPDATE
SET tipo_movimiento_reversion_id = EXCLUDED.tipo_movimiento_reversion_id,
    descripcion = EXCLUDED.descripcion,
    activo = TRUE;

-- 4.3. SAL_ORDEN + DEVOLUCION_TALLER -> DEV_TALLER
INSERT INTO admin.regla_reversion_movimiento (
    tipo_movimiento_origen_id,
    contexto_reversion,
    tipo_movimiento_reversion_id,
    descripcion
)
SELECT
    origen.tipo_movimiento_id,
    'DEVOLUCION_TALLER',
    reverso.tipo_movimiento_id,
    'Reversión de consumo de taller por devolución en orden'
FROM admin.tipo_movimiento_inventario origen
JOIN admin.tipo_movimiento_inventario reverso
  ON reverso.codigo = 'DEV_TALLER'
WHERE origen.codigo = 'SAL_ORDEN'
ON CONFLICT (tipo_movimiento_origen_id, contexto_reversion) DO UPDATE
SET tipo_movimiento_reversion_id = EXCLUDED.tipo_movimiento_reversion_id,
    descripcion = EXCLUDED.descripcion,
    activo = TRUE;

COMMIT;
