-- ============================================================================
-- MIGRATION: 033_billing_factura_anulacion_audit.sql
-- MODULE: Facturación (Auditoría Inmutable de Anulación de Facturas)
-- DESCRIPTION:
--   1. Crea tabla admin.factura_anulacion con PK INT4 GENERATED BY DEFAULT AS IDENTITY.
--   2. Registra snapshot histórico inmutable de la anulación (motivo, movimiento, destino, cantidades).
--   3. Restricción UNIQUE en factura_id para garantizar exactamente un registro por factura anulada.
-- IDEMPOTENT: Sí
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS admin.factura_anulacion (
    factura_anulacion_id            INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id                      INT4 NOT NULL,
    factura_id                      INT4 NOT NULL,
    motivo_anulacion_factura_id     INT4 NULL,

    -- Snapshot histórico del motivo
    codigo_motivo                   VARCHAR(50) NOT NULL,
    motivo_anulacion                VARCHAR(255) NOT NULL,
    descripcion_motivo              TEXT NULL,

    -- Snapshot histórico del movimiento de inventario asociado
    genera_movimiento               BOOLEAN NOT NULL DEFAULT FALSE,
    tipo_movimiento_reversion_id    INT4 NULL,
    codigo_movimiento_reversion     VARCHAR(50) NULL,
    nombre_movimiento_reversion     VARCHAR(150) NULL,

    -- Parámetros físicos y cantidades revertidas
    destino_producto                VARCHAR(50) NULL,
    cantidad_revertida              NUMERIC(14,4) NOT NULL DEFAULT 0,

    -- Observación ingresada por el usuario
    observacion                     TEXT NULL,

    -- Auditoría y Trazabilidad
    usuario_autorizacion_id         INT4 NULL,
    usuario_anulacion_id            INT4 NOT NULL,
    fecha_anulacion                 TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    fecha_registro                  TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),

    CONSTRAINT uq_factura_anulacion_factura
        UNIQUE (factura_id),

    CONSTRAINT fk_factura_anulacion_factura
        FOREIGN KEY (factura_id)
        REFERENCES admin.facturas(factura_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_factura_anulacion_motivo
        FOREIGN KEY (motivo_anulacion_factura_id)
        REFERENCES admin.motivo_anulacion_factura(motivo_anulacion_factura_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_factura_anulacion_tipo_mov
        FOREIGN KEY (tipo_movimiento_reversion_id)
        REFERENCES admin.tipo_movimiento_inventario(tipo_movimiento_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_factura_anulacion_usuario_anul
        FOREIGN KEY (usuario_anulacion_id)
        REFERENCES admin.usuario(usuario_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_factura_anulacion_usuario_aut
        FOREIGN KEY (usuario_autorizacion_id)
        REFERENCES admin.usuario(usuario_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_factura_anulacion_empresa
        FOREIGN KEY (empresa_id)
        REFERENCES admin.empresa(empresa_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_factura_anulacion_empresa 
    ON admin.factura_anulacion(empresa_id);

CREATE INDEX IF NOT EXISTS idx_factura_anulacion_factura 
    ON admin.factura_anulacion(factura_id);

CREATE INDEX IF NOT EXISTS idx_factura_anulacion_motivo 
    ON admin.factura_anulacion(motivo_anulacion_factura_id);

CREATE INDEX IF NOT EXISTS idx_factura_anulacion_tipo_mov 
    ON admin.factura_anulacion(tipo_movimiento_reversion_id);

COMMIT;
