-- ============================================================================
-- MIGRATION: 034_orden_tracking.sql
-- MODULE: Taller / Portal Público de Seguimiento (Ride Lab Tracking)
-- DESCRIPTION:
--   1. Crea tabla admin.orden_tracking con PK INT4 GENERATED BY DEFAULT AS IDENTITY.
--   2. Almacena token_hash (SHA-256) único para acceso público seguro sin exponer IDs internos.
--   3. Restricciones UNIQUE en orden_trabajo_id y token_hash.
--   4. Llave foránea hacia admin.ordenes_trabajo(orden_trabajo_id).
-- IDEMPOTENT: Sí
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS admin.orden_tracking (
    orden_tracking_id       INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id        INT4 NOT NULL,
    token_hash              VARCHAR(128) NOT NULL,
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion          TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    fecha_ultimo_acceso     TIMESTAMPTZ NULL,
    fecha_desactivacion     TIMESTAMPTZ NULL,
    usuario_registro        INT4 NULL,

    CONSTRAINT uq_orden_tracking_orden_trabajo
        UNIQUE (orden_trabajo_id),

    CONSTRAINT uq_orden_tracking_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_orden_tracking_orden_trabajo
        FOREIGN KEY (orden_trabajo_id)
        REFERENCES admin.ordenes_trabajo(orden_trabajo_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_orden_tracking_hash
    ON admin.orden_tracking (token_hash);

CREATE INDEX IF NOT EXISTS idx_orden_tracking_ot
    ON admin.orden_tracking (orden_trabajo_id);

CREATE INDEX IF NOT EXISTS idx_orden_tracking_activo
    ON admin.orden_tracking (activo);

COMMIT;
