-- ============================================================================
-- MIGRATION: 036_user_session_duration.sql
-- MODULE: Seguridad / Sesiones de Usuario
-- DESCRIPTION:
--   1. Agrega duracion_sesion_minutos a admin.usuario con DEFAULT 480 (8 horas) y CHECK >= 1.
--   2. Convierte admin.usuario_sesion.sesion_id a GENERATED BY DEFAULT AS IDENTITY
--      sin recrear la tabla, preservando todos los IDs históricos y sincronizando la secuencia.
-- IDEMPOTENT: Sí
-- ============================================================================

BEGIN;

-- 1. Agregar columna duracion_sesion_minutos a admin.usuario
ALTER TABLE admin.usuario
ADD COLUMN IF NOT EXISTS duracion_sesion_minutos INT4 NOT NULL DEFAULT 480;

-- 2. Asegurar que registros existentes tengan el valor por defecto si hubiera nulls
UPDATE admin.usuario
SET duracion_sesion_minutos = 480
WHERE duracion_sesion_minutos IS NULL OR duracion_sesion_minutos < 1;

-- 3. Constraint CHECK duracion_sesion_minutos >= 1
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_usuario_duracion_sesion_minutos'
    ) THEN
        ALTER TABLE admin.usuario
        ADD CONSTRAINT chk_usuario_duracion_sesion_minutos
        CHECK (duracion_sesion_minutos >= 1);
    END IF;
END $$;

-- 4. Convertir admin.usuario_sesion.sesion_id a GENERATED BY DEFAULT AS IDENTITY
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 
        FROM information_schema.columns 
        WHERE table_schema = 'admin' 
          AND table_name = 'usuario_sesion' 
          AND column_name = 'sesion_id' 
          AND is_identity = 'YES'
    ) THEN
        ALTER TABLE admin.usuario_sesion 
        ALTER COLUMN sesion_id ADD GENERATED BY DEFAULT AS IDENTITY;

        EXECUTE format(
            'ALTER TABLE admin.usuario_sesion ALTER COLUMN sesion_id RESTART WITH %s',
            COALESCE((SELECT MAX(sesion_id) FROM admin.usuario_sesion), 0) + 1
        );
    END IF;
END $$;

COMMIT;
