-- ============================================================================
-- MIGRATION: 038_notificacion_orden_trabajo.sql
-- MODULE: Taller / Notificaciones SMS con TextBee
-- DESCRIPTION:
--   1. Crea la tabla admin.notificacion_orden_trabajo para auditoría y trazabilidad
--      de notificaciones SMS enviadas a clientes (BIENVENIDA, ESTADO, CIERRE).
--   2. Agrega constraints de validación de tipos y estados de notificación.
--   3. Crea índices para búsquedas por orden, empresa y control de idempotencia.
-- IDEMPOTENT: Sí
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS admin.notificacion_orden_trabajo (
    notificacion_orden_trabajo_id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa_id INT4 NOT NULL REFERENCES admin.empresa(empresa_id),
    orden_trabajo_id INT4 NOT NULL REFERENCES admin.ordenes_trabajo(orden_trabajo_id),
    tipo_notificacion VARCHAR(32) NOT NULL,
    telefono_destino VARCHAR(32) NULL,
    mensaje VARCHAR(255) NOT NULL,
    estado_envio VARCHAR(32) NOT NULL,
    codigo_http INT4 NULL,
    respuesta_proveedor JSONB NULL,
    error_mensaje TEXT NULL,
    fecha_envio TIMESTAMPTZ NULL,
    fecha_registro TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    usuario_registro INT4 NULL REFERENCES admin.usuario(usuario_id),
    CONSTRAINT chk_notif_tipo CHECK (tipo_notificacion IN ('BIENVENIDA', 'ESTADO', 'CIERRE')),
    CONSTRAINT chk_notif_estado CHECK (estado_envio IN ('ENVIADO', 'ERROR', 'NO_ENVIADO'))
);

-- Índices de consulta frecuente
CREATE INDEX IF NOT EXISTS idx_notif_ot_tipo_estado
    ON admin.notificacion_orden_trabajo (orden_trabajo_id, tipo_notificacion, estado_envio);

CREATE INDEX IF NOT EXISTS idx_notif_empresa_id
    ON admin.notificacion_orden_trabajo (empresa_id);

CREATE INDEX IF NOT EXISTS idx_notif_fecha_registro
    ON admin.notificacion_orden_trabajo (fecha_registro DESC);

-- Índices únicos parciales para garantizar idempotencia a nivel de base de datos
CREATE UNIQUE INDEX IF NOT EXISTS uq_notif_ot_bienvenida_enviado
    ON admin.notificacion_orden_trabajo (orden_trabajo_id)
    WHERE (tipo_notificacion = 'BIENVENIDA' AND estado_envio = 'ENVIADO');

CREATE UNIQUE INDEX IF NOT EXISTS uq_notif_ot_cierre_enviado
    ON admin.notificacion_orden_trabajo (orden_trabajo_id)
    WHERE (tipo_notificacion = 'CIERRE' AND estado_envio = 'ENVIADO');

COMMIT;
