import { PoolClient } from "pg";

export interface ReglaReversion {
  regla_reversion_movimiento_id: number;
  tipo_movimiento_origen_id: number;
  contexto_reversion: string;
  tipo_movimiento_reversion_id: number;
  codigo_reversion: string;
  nombre_reversion: string;
  naturaleza_reversion: string;
  descripcion: string | null;
}

export interface LineaMovimientoReversion {
  detalle_factura_id: number;
  producto_id: number;
  almacen_id: number;
  descripcion: string;
  cantidad: number;
  movimiento_inventario_id: number;
  tipo_movimiento_origen_id: number;
  tipo_movimiento_origen_codigo: string;
  tipo_movimiento_origen_nombre: string;
  naturaleza_origen: string;
  costo_unitario_historico: number;
  costo_total_historico: number;
  codigo_movimiento_origen: string | null;
  orden_trabajo_id?: number | null;
  orden_producto_id?: number | null;
  origen_trazabilidad: "DIRECTO" | "HISTORICO_SANEADO";
}

export interface ReversionTraceabilityError {
  code: "MOVIMIENTO_ORIGEN_NO_ENCONTRADO" | "MOVIMIENTO_ORIGEN_AMBIGUO" | "MOVIMIENTO_YA_REVERTIDO" | "REGLA_REVERSION_NO_CONFIGURADA" | "MOVIMIENTO_EMPRESA_INVALIDA";
  message: string;
  details?: Record<string, unknown>;
}

/**
 * Asegura la existencia de las tablas de trazabilidad y reglas de reversión en el schema admin.
 * Totalmente idempotente: utiliza PKs INT4 GENERATED BY DEFAULT AS IDENTITY.
 */
export async function ensureReversalTraceabilitySchema(client: PoolClient): Promise<void> {
  await client.query(`
    -- 1. Columna movimiento_origen_id en admin.movimientos_inventario
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'admin'
              AND table_name = 'movimientos_inventario'
              AND column_name = 'movimiento_origen_id'
        ) THEN
            ALTER TABLE admin.movimientos_inventario
            ADD COLUMN movimiento_origen_id INT4 NULL;
        END IF;
    END $$;

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = 'admin'
              AND table_name = 'movimientos_inventario'
              AND constraint_name = 'movimientos_movimiento_origen_fk'
        ) THEN
            ALTER TABLE admin.movimientos_inventario
            ADD CONSTRAINT movimientos_movimiento_origen_fk
            FOREIGN KEY (movimiento_origen_id)
            REFERENCES admin.movimientos_inventario (movimiento_inventario_id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;
        END IF;
    END $$;

    CREATE INDEX IF NOT EXISTS idx_movimientos_movimiento_origen
    ON admin.movimientos_inventario (movimiento_origen_id)
    WHERE movimiento_origen_id IS NOT NULL;

    -- 2. Tabla admin.detalle_factura_movimiento
    CREATE TABLE IF NOT EXISTS admin.detalle_factura_movimiento (
        detalle_factura_movimiento_id INT4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        detalle_factura_id INT4 NOT NULL,
        movimiento_inventario_id INT4 NOT NULL,
        cantidad NUMERIC(14,4) NOT NULL,
        fecha_registro TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
        usuario_registro INT4 NULL,

        CONSTRAINT pk_detalle_factura_movimiento
            PRIMARY KEY (detalle_factura_movimiento_id),

        CONSTRAINT fk_dfm_detalle_factura
            FOREIGN KEY (detalle_factura_id)
            REFERENCES admin.detalle_factura(detalle_factura_id),

        CONSTRAINT fk_dfm_movimiento
            FOREIGN KEY (movimiento_inventario_id)
            REFERENCES admin.movimientos_inventario(movimiento_inventario_id),

        CONSTRAINT uq_dfm_detalle_movimiento
            UNIQUE (detalle_factura_id, movimiento_inventario_id),

        CONSTRAINT ck_dfm_cantidad
            CHECK (cantidad > 0)
    );

    CREATE INDEX IF NOT EXISTS idx_dfm_detalle_factura
    ON admin.detalle_factura_movimiento (detalle_factura_id);

    CREATE INDEX IF NOT EXISTS idx_dfm_movimiento
    ON admin.detalle_factura_movimiento (movimiento_inventario_id);

    -- 3. Tabla admin.regla_reversion_movimiento
    CREATE TABLE IF NOT EXISTS admin.regla_reversion_movimiento (
        regla_reversion_movimiento_id INT4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        tipo_movimiento_origen_id INT4 NOT NULL,
        contexto_reversion VARCHAR(50) NOT NULL,
        tipo_movimiento_reversion_id INT4 NOT NULL,
        activo BOOLEAN NOT NULL DEFAULT TRUE,
        descripcion VARCHAR(255) NULL,
        fecha_registro TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
        fecha_actualizacion TIMESTAMPTZ NULL,
        usuario_registro INT4 NULL,
        usuario_actualizacion INT4 NULL,

        CONSTRAINT pk_regla_reversion_movimiento
            PRIMARY KEY (regla_reversion_movimiento_id),

        CONSTRAINT fk_reg_rev_origen
            FOREIGN KEY (tipo_movimiento_origen_id)
            REFERENCES admin.tipo_movimiento_inventario(tipo_movimiento_id),

        CONSTRAINT fk_reg_rev_destino
            FOREIGN KEY (tipo_movimiento_reversion_id)
            REFERENCES admin.tipo_movimiento_inventario(tipo_movimiento_id),

        CONSTRAINT uq_regla_reversion
            UNIQUE (tipo_movimiento_origen_id, contexto_reversion)
    );

    CREATE INDEX IF NOT EXISTS idx_reg_rev_origen
    ON admin.regla_reversion_movimiento (tipo_movimiento_origen_id);

    CREATE INDEX IF NOT EXISTS idx_reg_rev_contexto
    ON admin.regla_reversion_movimiento (contexto_reversion);

    CREATE INDEX IF NOT EXISTS idx_reg_rev_activo
    ON admin.regla_reversion_movimiento (activo);

    -- 4. Reglas iniciales sin IDs hardcodeados
    INSERT INTO admin.regla_reversion_movimiento (
        tipo_movimiento_origen_id,
        contexto_reversion,
        tipo_movimiento_reversion_id,
        descripcion
    )
    SELECT
        origen.tipo_movimiento_id,
        'ANULACION_FACTURA',
        reverso.tipo_movimiento_id,
        'Reversión de salida comercial por anulación de factura'
    FROM admin.tipo_movimiento_inventario origen
    JOIN admin.tipo_movimiento_inventario reverso
      ON reverso.codigo = 'DEV_VENTA'
    WHERE origen.codigo = 'SAL_VENTA'
    ON CONFLICT (tipo_movimiento_origen_id, contexto_reversion) DO UPDATE
    SET tipo_movimiento_reversion_id = EXCLUDED.tipo_movimiento_reversion_id,
        descripcion = EXCLUDED.descripcion,
        activo = TRUE;

    INSERT INTO admin.regla_reversion_movimiento (
        tipo_movimiento_origen_id,
        contexto_reversion,
        tipo_movimiento_reversion_id,
        descripcion
    )
    SELECT
        origen.tipo_movimiento_id,
        'ANULACION_FACTURA',
        reverso.tipo_movimiento_id,
        'Reversión de consumo de orden de trabajo por anulación de factura'
    FROM admin.tipo_movimiento_inventario origen
    JOIN admin.tipo_movimiento_inventario reverso
      ON reverso.codigo = 'DEV_VENTA'
    WHERE origen.codigo = 'SAL_ORDEN'
    ON CONFLICT (tipo_movimiento_origen_id, contexto_reversion) DO UPDATE
    SET tipo_movimiento_reversion_id = EXCLUDED.tipo_movimiento_reversion_id,
        descripcion = EXCLUDED.descripcion,
        activo = TRUE;

    INSERT INTO admin.regla_reversion_movimiento (
        tipo_movimiento_origen_id,
        contexto_reversion,
        tipo_movimiento_reversion_id,
        descripcion
    )
    SELECT
        origen.tipo_movimiento_id,
        'DEVOLUCION_TALLER',
        reverso.tipo_movimiento_id,
        'Reversión de consumo de taller por devolución en orden'
    FROM admin.tipo_movimiento_inventario origen
    JOIN admin.tipo_movimiento_inventario reverso
      ON reverso.codigo = 'DEV_TALLER'
    WHERE origen.codigo = 'SAL_ORDEN'
    ON CONFLICT (tipo_movimiento_origen_id, contexto_reversion) DO UPDATE
    SET tipo_movimiento_reversion_id = EXCLUDED.tipo_movimiento_reversion_id,
        descripcion = EXCLUDED.descripcion,
        activo = TRUE;
  `);
}

/**
 * Consulta la regla de reversión aplicable para un tipo de movimiento origen y contexto.
 * NO utiliza IDs hardcodeados ni nombres fijos de movimientos.
 */
export async function obtenerReglaReversion(
  client: PoolClient,
  tipoMovimientoOrigenId: number,
  contextoReversion: string = "ANULACION_FACTURA"
): Promise<ReglaReversion | null> {
  const res = await client.query<ReglaReversion>(
    `SELECT
       rrm.regla_reversion_movimiento_id,
       rrm.tipo_movimiento_origen_id,
       rrm.contexto_reversion,
       rrm.tipo_movimiento_reversion_id,
       tm_rev.codigo AS codigo_reversion,
       tm_rev.nombre AS nombre_reversion,
       tm_rev.naturaleza AS naturaleza_reversion,
       rrm.descripcion
     FROM admin.regla_reversion_movimiento rrm
     JOIN admin.tipo_movimiento_inventario tm_rev
       ON rrm.tipo_movimiento_reversion_id = tm_rev.tipo_movimiento_id
     WHERE rrm.tipo_movimiento_origen_id = $1
       AND rrm.contexto_reversion = $2
       AND rrm.activo = true
     LIMIT 1;`,
    [tipoMovimientoOrigenId, contextoReversion]
  );
  return res.rows[0] || null;
}

/**
 * Registra la relación explícita entre una línea de detalle_factura y un movimiento real de inventario.
 */
export async function registrarDetalleFacturaMovimiento(
  client: PoolClient,
  detalleFacturaId: number,
  movimientoInventarioId: number,
  cantidad: number,
  usuarioId?: number | null
): Promise<void> {
  if (cantidad <= 0) return;
  await client.query(
    `INSERT INTO admin.detalle_factura_movimiento (
       detalle_factura_id,
       movimiento_inventario_id,
       cantidad,
       usuario_registro
     ) VALUES ($1, $2, $3, $4)
     ON CONFLICT (detalle_factura_id, movimiento_inventario_id) DO UPDATE
     SET cantidad = EXCLUDED.cantidad;`,
    [detalleFacturaId, movimientoInventarioId, cantidad, usuarioId ?? null]
  );
}

/**
 * Valida si un movimiento origen ya fue revertido en el sistema para impedir doble reversión.
 */
export async function validarDobleReversion(
  client: PoolClient,
  movimientoOrigenId: number,
  empresaId: number
): Promise<{ yaRevertido: boolean; movimientoReversoId?: number }> {
  const res = await client.query<{ movimiento_inventario_id: number }>(
    `SELECT movimiento_inventario_id
     FROM admin.movimientos_inventario
     WHERE movimiento_origen_id = $1
       AND empresa_id = $2
     LIMIT 1;`,
    [movimientoOrigenId, empresaId]
  );

  if (res.rows && res.rows.length > 0) {
    return {
      yaRevertido: true,
      movimientoReversoId: res.rows[0].movimiento_inventario_id
    };
  }

  return { yaRevertido: false };
}

/**
 * Obtiene y valida los movimientos de inventario que deben revertirse para una factura.
 *
 * Flujo:
 * 1. Lee líneas físicas de detalle_factura.
 * 2. Consulta admin.detalle_factura_movimiento para cada línea.
 * 3. Si no existe registro (factura histórica):
 *    Aplica fallback estricto:
 *    - Si encuentra EXACTAMENTE 1 movimiento compatible -> lo utiliza y sanea admin.detalle_factura_movimiento.
 *    - Si encuentra 0 movimientos -> Bloquea con MOVIMIENTO_ORIGEN_NO_ENCONTRADO.
 *    - Si encuentra >1 movimientos ambiguos -> Bloquea con MOVIMIENTO_ORIGEN_AMBIGUO (NO usa LIMIT 1 ni primero/último).
 */
export async function resolverMovimientosParaReversionFactura(
  client: PoolClient,
  facturaId: number,
  empresaId: number,
  contextoReversion: string = "ANULACION_FACTURA"
): Promise<{
  exito: boolean;
  movimientos: LineaMovimientoReversion[];
  error?: ReversionTraceabilityError;
}> {
  // Descubrir columnas reales
  const colsRes = await client.query<{ table_name: string; column_name: string }>(
    `SELECT table_name, column_name 
     FROM information_schema.columns 
     WHERE table_schema = 'admin' 
       AND table_name IN ('facturas', 'detalle_factura', 'movimientos_inventario')`
  );
  const facCols = new Set<string>();
  const detCols = new Set<string>();
  const movCols = new Set<string>();
  for (const row of colsRes.rows) {
    if (row.table_name === "facturas") facCols.add(row.column_name.toLowerCase());
    if (row.table_name === "detalle_factura") detCols.add(row.column_name.toLowerCase());
    if (row.table_name === "movimientos_inventario") movCols.add(row.column_name.toLowerCase());
  }

  const colFacCodigo = facCols.has("codigo_factura")
    ? "f.codigo_factura"
    : "'FAC-' || f.factura_id::text AS codigo_factura";
  const colFacNumero = facCols.has("numero_factura")
    ? "f.numero_factura"
    : (facCols.has("codigo_factura") ? "f.codigo_factura" : "'FAC-' || f.factura_id::text") + " AS numero_factura";
  const colFacOt = facCols.has("orden_trabajo_id") ? "f.orden_trabajo_id" : "NULL::int AS orden_trabajo_id";

  // 1. Obtener datos de la cabecera de la factura
  const facRes = await client.query<{
    factura_id: number;
    codigo_factura: string;
    numero_factura: string | null;
    orden_trabajo_id: number | null;
  }>(
    `SELECT f.factura_id, ${colFacCodigo}, ${colFacNumero}, ${colFacOt}
     FROM admin.facturas f
     WHERE f.factura_id = $1 AND f.empresa_id = $2;`,
    [facturaId, empresaId]
  );

  if (!facRes.rows || facRes.rows.length === 0) {
    return {
      exito: false,
      movimientos: [],
      error: {
        code: "MOVIMIENTO_ORIGEN_NO_ENCONTRADO",
        message: `La factura con ID ${facturaId} no existe o no pertenece a la empresa.`
      }
    };
  }

  const factura = facRes.rows[0];
  const codigoFactura = factura.codigo_factura || `FAC-${facturaId}`;
  const numeroFactura = factura.numero_factura || codigoFactura;
  let ordenTrabajoId = factura.orden_trabajo_id ? Number(factura.orden_trabajo_id) : null;

  // 2. Obtener detalle de líneas de la factura
  const exprDetTipoLinea = detCols.has("tipo_linea")
    ? "df.tipo_linea"
    : (detCols.has("tipo_detalle") ? "COALESCE(df.tipo_detalle, 'PRODUCTO')" : "'PRODUCTO'");

  const detRes = await client.query<{
    detalle_factura_id: number;
    factura_id: number;
    almacen_id: number | null;
    tipo_linea: string;
    producto_id: number | null;
    orden_producto_id: number | null;
    orden_servicio_id: number | null;
    cantidad: number;
    costo_unitario: number | null;
    descripcion: string;
  }>(
    `SELECT
       df.detalle_factura_id,
       df.factura_id,
       ${detCols.has("almacen_id") ? "df.almacen_id" : "NULL::int AS almacen_id"},
       COALESCE(${exprDetTipoLinea}, 'PRODUCTO') AS tipo_linea,
       df.producto_id,
       ${detCols.has("orden_producto_id") ? "df.orden_producto_id" : "NULL::int AS orden_producto_id"},
       ${detCols.has("orden_servicio_id") ? "df.orden_servicio_id" : "NULL::int AS orden_servicio_id"},
       df.cantidad,
       ${detCols.has("costo_unitario") ? "df.costo_unitario" : "NULL::numeric AS costo_unitario"},
       df.descripcion
     FROM admin.detalle_factura df
     WHERE df.factura_id = $1
     ORDER BY df.detalle_factura_id ASC;`,
    [facturaId]
  );

  const detalles = detRes.rows || [];

  // Resolver ordenTrabajoId si no vino en cabecera
  if (!ordenTrabajoId) {
    const lineaConOp = detalles.find((d) => d.orden_producto_id);
    if (lineaConOp?.orden_producto_id) {
      const opRes = await client.query<{ orden_trabajo_id: number }>(
        `SELECT orden_trabajo_id FROM admin.orden_productos WHERE orden_producto_id = $1 LIMIT 1;`,
        [Number(lineaConOp.orden_producto_id)]
      ).catch(() => ({ rows: [] }));
      if (opRes.rows[0]?.orden_trabajo_id) {
        ordenTrabajoId = Number(opRes.rows[0].orden_trabajo_id);
      }
    }
  }

  // Filtrar únicamente líneas físicas que implican producto/repuesto (los servicios NO mueven inventario)
  const lineasFisicas = detalles.filter(
    (d) => String(d.tipo_linea).toUpperCase() !== "SERVICIO" && !d.orden_servicio_id && d.producto_id
  );

  const movimientosARevertir: LineaMovimientoReversion[] = [];

  for (const linea of lineasFisicas) {
    const prodId = Number(linea.producto_id);
    const cantFacturada = parseFloat(String(linea.cantidad || 0));
    if (cantFacturada <= 0) continue;

    // A) Paso 1: Trazabilidad explícita en admin.detalle_factura_movimiento
    const dfmRes = await client.query<{
      detalle_factura_movimiento_id: number;
      movimiento_inventario_id: number;
      cantidad: number;
      empresa_id: number;
      producto_id: number;
      almacen_id: number;
      costo_unitario: number;
      costo_total: number;
      codigo_movimiento: string | null;
      tipo_movimiento_id: number;
      tipo_movimiento_codigo: string;
      tipo_movimiento_nombre: string;
      naturaleza: string;
      orden_trabajo_id: number | null;
      orden_producto_id: number | null;
    }>(
      `SELECT
         dfm.detalle_factura_movimiento_id,
         dfm.movimiento_inventario_id,
         dfm.cantidad,
         mi.empresa_id,
         mi.producto_id,
         mi.almacen_id,
         mi.costo_unitario,
         mi.costo_total,
         mi.codigo_movimiento,
         mi.tipo_movimiento_id,
         tm.codigo AS tipo_movimiento_codigo,
         tm.nombre AS tipo_movimiento_nombre,
         tm.naturaleza,
         mi.orden_trabajo_id,
         mi.orden_producto_id
       FROM admin.detalle_factura_movimiento dfm
       JOIN admin.movimientos_inventario mi
         ON dfm.movimiento_inventario_id = mi.movimiento_inventario_id
       JOIN admin.tipo_movimiento_inventario tm
         ON mi.tipo_movimiento_id = tm.tipo_movimiento_id
       WHERE dfm.detalle_factura_id = $1;`,
      [linea.detalle_factura_id]
    );

    if (dfmRes.rows && dfmRes.rows.length > 0) {
      for (const row of dfmRes.rows) {
        // Validación Multitenancy
        if (Number(row.empresa_id) !== empresaId) {
          return {
            exito: false,
            movimientos: [],
            error: {
              code: "MOVIMIENTO_EMPRESA_INVALIDA",
              message: `Aislamiento multitenant: El movimiento de inventario #${row.movimiento_inventario_id} no pertenece a la empresa #${empresaId}.`
            }
          };
        }

        // Control de doble reversión
        const checkDoble = await validarDobleReversion(client, row.movimiento_inventario_id, empresaId);
        if (checkDoble.yaRevertido) {
          return {
            exito: false,
            movimientos: [],
            error: {
              code: "MOVIMIENTO_YA_REVERTIDO",
              message: `El movimiento de salida #${row.movimiento_inventario_id} del producto '${linea.descripcion}' ya fue revertido previamente en el movimiento #${checkDoble.movimientoReversoId}.`,
              details: {
                movimiento_inventario_id: row.movimiento_inventario_id,
                movimiento_reverso_id: checkDoble.movimientoReversoId
              }
            }
          };
        }

        // Validar que exista regla de reversión configurada
        const regla = await obtenerReglaReversion(client, row.tipo_movimiento_id, contextoReversion);
        if (!regla) {
          return {
            exito: false,
            movimientos: [],
            error: {
              code: "REGLA_REVERSION_NO_CONFIGURADA",
              message: `No existe una regla de reversión activa configurada para el tipo de movimiento '${row.tipo_movimiento_codigo}' en el contexto '${contextoReversion}'.`,
              details: {
                tipo_movimiento_origen_id: row.tipo_movimiento_id,
                tipo_movimiento_codigo: row.tipo_movimiento_codigo,
                contexto_reversion: contextoReversion
              }
            }
          };
        }

        movimientosARevertir.push({
          detalle_factura_id: linea.detalle_factura_id,
          producto_id: prodId,
          almacen_id: row.almacen_id,
          descripcion: linea.descripcion,
          cantidad: parseFloat(String(row.cantidad || cantFacturada)),
          movimiento_inventario_id: row.movimiento_inventario_id,
          tipo_movimiento_origen_id: row.tipo_movimiento_id,
          tipo_movimiento_origen_codigo: row.tipo_movimiento_codigo,
          tipo_movimiento_origen_nombre: row.tipo_movimiento_nombre,
          naturaleza_origen: row.naturaleza,
          costo_unitario_historico: parseFloat(String(row.costo_unitario || linea.costo_unitario || 0)),
          costo_total_historico: parseFloat(String(row.costo_total || (cantFacturada * (row.costo_unitario || 0)))),
          codigo_movimiento_origen: row.codigo_movimiento,
          orden_trabajo_id: row.orden_trabajo_id,
          orden_producto_id: row.orden_producto_id,
          origen_trazabilidad: "DIRECTO"
        });
      }
      continue;
    }

    // B) Paso 2: Fallback histórico estricto (Facturas sin trazabilidad previa en admin.detalle_factura_movimiento)
    const ordenProdId = linea.orden_producto_id ? Number(linea.orden_producto_id) : null;
    const refShort = `FAC-${facturaId}`;
    const refIdStr = String(facturaId);

    const fallbackCandidatesRes = await client.query<{
      movimiento_inventario_id: number;
      empresa_id: number;
      producto_id: number;
      almacen_id: number;
      cantidad: number;
      costo_unitario: number;
      costo_total: number;
      codigo_movimiento: string | null;
      tipo_movimiento_id: number;
      tipo_movimiento_codigo: string;
      tipo_movimiento_nombre: string;
      naturaleza: string;
      orden_trabajo_id: number | null;
      orden_producto_id: number | null;
    }>(
      `SELECT
         mi.movimiento_inventario_id,
         mi.empresa_id,
         mi.producto_id,
         mi.almacen_id,
         mi.cantidad,
         mi.costo_unitario,
         mi.costo_total,
         mi.codigo_movimiento,
         mi.tipo_movimiento_id,
         tm.codigo AS tipo_movimiento_codigo,
         tm.nombre AS tipo_movimiento_nombre,
         tm.naturaleza,
         mi.orden_trabajo_id,
         mi.orden_producto_id
       FROM admin.movimientos_inventario mi
       JOIN admin.tipo_movimiento_inventario tm
         ON mi.tipo_movimiento_id = tm.tipo_movimiento_id
       WHERE mi.empresa_id = $1
         AND mi.producto_id = $2
         AND tm.naturaleza = 'SALIDA'
         AND NOT EXISTS (
           SELECT 1
           FROM admin.movimientos_inventario rev
           WHERE rev.movimiento_origen_id = mi.movimiento_inventario_id
         )
         AND (
           -- 1. Coincidencia estructural con línea de orden de repuesto
           ($3::int IS NOT NULL AND mi.orden_producto_id = $3::int)
           OR
           -- 2. Coincidencia estructural con orden de trabajo
           ($4::int IS NOT NULL AND mi.orden_trabajo_id = $4::int)
           OR
           -- 3. Coincidencia por referencia de factura o codigo_factura
            (
              TRIM(mi.referencia) = $5
              OR TRIM(mi.referencia) = $6
              OR TRIM(mi.referencia) = $7
              OR TRIM(mi.referencia) = $8
              OR mi.referencia ILIKE '%' || $5 || '%'
              OR (mi.observacion IS NOT NULL AND mi.observacion ILIKE '%' || $5 || '%')
              ${movCols.has("codigo_factura") ? "OR (mi.codigo_factura IS NOT NULL AND (TRIM(mi.codigo_factura) = $5 OR TRIM(mi.codigo_factura) = $6))" : ""}
            )
           OR
           -- 4. Coincidencia por referencia de OT
           ($4::int IS NOT NULL AND (
             TRIM(mi.referencia) ILIKE '%OT-' || $4::text || '%'
             OR mi.observacion ILIKE '%OT #' || $4::text || '%'
           ))
         );`,
      [
        empresaId,      // $1
        prodId,         // $2
        ordenProdId,    // $3
        ordenTrabajoId, // $4
        codigoFactura,  // $5
        numeroFactura,  // $6
        refShort,       // $7
        refIdStr        // $8
      ]
    );

    const candidates = fallbackCandidatesRes.rows || [];

    // Regla Sección 12: Bloquear si 0 movimientos
    if (candidates.length === 0) {
      return {
        exito: false,
        movimientos: [],
        error: {
          code: "MOVIMIENTO_ORIGEN_NO_ENCONTRADO",
          message: `No se encontró la salida original de inventario para el producto '${linea.descripcion}' (#${prodId}) en la factura ${codigoFactura}.`,
          details: {
            factura_id: facturaId,
            producto_id: prodId,
            detalle_factura_id: linea.detalle_factura_id
          }
        }
      };
    }

    // Regla Sección 12: Bloquear si más de 1 candidato ambiguo (NO escoger LIMIT 1 ni primero/último)
    if (candidates.length > 1) {
      return {
        exito: false,
        movimientos: [],
        error: {
          code: "MOVIMIENTO_ORIGEN_AMBIGUO",
          message: `Se encontraron múltiples (${candidates.length}) movimientos de salida candidatos para el producto '${linea.descripcion}' (#${prodId}) en la factura ${codigoFactura}. No se puede seleccionar automáticamente para evitar inconsistencias contables.`,
          details: {
            factura_id: facturaId,
            producto_id: prodId,
            detalle_factura_id: linea.detalle_factura_id,
            candidatos_encontrados: candidates.map((c) => ({
              movimiento_inventario_id: c.movimiento_inventario_id,
              tipo_movimiento_codigo: c.tipo_movimiento_codigo,
              cantidad: c.cantidad,
              almacen_id: c.almacen_id
            }))
          }
        }
      };
    }

    // EXACTAMENTE 1 candidato: saneamiento y uso
    const matched = candidates[0];

    // Validar regla de reversión
    const regla = await obtenerReglaReversion(client, matched.tipo_movimiento_id, contextoReversion);
    if (!regla) {
      return {
        exito: false,
        movimientos: [],
        error: {
          code: "REGLA_REVERSION_NO_CONFIGURADA",
          message: `No existe una regla de reversión activa configurada para el tipo de movimiento '${matched.tipo_movimiento_codigo}' en el contexto '${contextoReversion}'.`,
          details: {
            tipo_movimiento_origen_id: matched.tipo_movimiento_id,
            tipo_movimiento_codigo: matched.tipo_movimiento_codigo,
            contexto_reversion: contextoReversion
          }
        }
      };
    }

    // Sanear relación en admin.detalle_factura_movimiento para dejar registrada la trazabilidad
    try {
      await registrarDetalleFacturaMovimiento(
        client,
        linea.detalle_factura_id,
        matched.movimiento_inventario_id,
        cantFacturada,
        null
      );
    } catch (eTrace) {
      console.warn("Could not backfill detalle_factura_movimiento in fallback:", eTrace);
    }

    movimientosARevertir.push({
      detalle_factura_id: linea.detalle_factura_id,
      producto_id: prodId,
      almacen_id: matched.almacen_id,
      descripcion: linea.descripcion,
      cantidad: cantFacturada,
      movimiento_inventario_id: matched.movimiento_inventario_id,
      tipo_movimiento_origen_id: matched.tipo_movimiento_id,
      tipo_movimiento_origen_codigo: matched.tipo_movimiento_codigo,
      tipo_movimiento_origen_nombre: matched.tipo_movimiento_nombre,
      naturaleza_origen: matched.naturaleza,
      costo_unitario_historico: parseFloat(String(matched.costo_unitario || linea.costo_unitario || 0)),
      costo_total_historico: parseFloat(String(matched.costo_total || (cantFacturada * (matched.costo_unitario || 0)))),
      codigo_movimiento_origen: matched.codigo_movimiento,
      orden_trabajo_id: matched.orden_trabajo_id,
      orden_producto_id: matched.orden_producto_id,
      origen_trazabilidad: "HISTORICO_SANEADO"
    });
  }

  return {
    exito: true,
    movimientos: movimientosARevertir
  };
}
